server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: COVAN-PRODUCER
        uri: lb://USER-SERVICE
        predicates:
          - Path=/users/**
      - id: COVAN-ANALYSE
        uri: lb://COVAN-ANALYSE
        predicates:
          - Path=/analyse/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

